import {Engine} from 'https://cdn.jsdelivr.net/npm/@babylonjs/core@9.28.0/Engines/engine.js';
import {Scene} from 'https://cdn.jsdelivr.net/npm/@babylonjs/core@9.28.0/scene.js';
import {Vector3,Color3,Color4} from 'https://cdn.jsdelivr.net/npm/@babylonjs/core@9.28.0/Maths/math.js';
import {FreeCamera} from 'https://cdn.jsdelivr.net/npm/@babylonjs/core@9.28.0/Cameras/freeCamera.js';
import {HemisphericLight} from 'https://cdn.jsdelivr.net/npm/@babylonjs/core@9.28.0/Lights/hemisphericLight.js';
import {DirectionalLight} from 'https://cdn.jsdelivr.net/npm/@babylonjs/core@9.28.0/Lights/directionalLight.js';
import {MeshBuilder} from 'https://cdn.jsdelivr.net/npm/@babylonjs/core@9.28.0/Meshes/meshBuilder.js';
import {TransformNode} from 'https://cdn.jsdelivr.net/npm/@babylonjs/core@9.28.0/Meshes/transformNode.js';
import {StandardMaterial} from 'https://cdn.jsdelivr.net/npm/@babylonjs/core@9.28.0/Materials/standardMaterial.js';

const $=s=>document.querySelector(s), canvas=$('#game'), loading=$('#loading'), missionEl=$('#mission'), distanceEl=$('#distance'), dialogEl=$('#dialog'), timerEl=$('#timer'), timeBadge=$('#timeBadge'), bossHud=$('#bossHud'), bossName=$('#bossName'), bossHp=$('#bossHp'), bossTip=$('#bossTip'), toastEl=$('#toast');
const talkBtn=$('#talkBtn'),trapBtn=$('#trapBtn'),strikeBtn=$('#strikeBtn'),jumpBtn=$('#jumpBtn');
const mobile=matchMedia('(max-width:760px)').matches;
window.__gameState={engine:'Babylon.js',ready:false,stage:0,fps:0,events:0,version:'next-0.1'};
const eventLog=[];
function emit(event,payload={}){const row={event,payload,at:Date.now()};eventLog.push(row);window.__gameState.events=eventLog.length;try{parent.postMessage({source:'ULMOA_GARDEN_EVENT',event,payload},'*')}catch{} }
function setMission(text,sub='빨간 목표 표시를 따라가요'){missionEl.textContent=text;distanceEl.textContent=sub;emit('quest',{stage,text});}
let dialogTimer=0;function say(html,ms=9000){dialogEl.innerHTML=html;dialogEl.classList.add('show');clearTimeout(dialogTimer);dialogTimer=setTimeout(()=>dialogEl.classList.remove('show'),ms)}
let toastTimer=0;function toast(text,ms=1800){toastEl.textContent=text;toastEl.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toastEl.classList.remove('show'),ms)}

const engine=new Engine(canvas,false,{preserveDrawingBuffer:false,stencil:false,antialias:false,adaptToDeviceRatio:false,powerPreference:'high-performance'});
engine.setHardwareScalingLevel(mobile?1.55:1.15);
const scene=new Scene(engine);scene.clearColor=new Color4(.55,.74,.92,1);scene.skipPointerMovePicking=true;scene.ambientColor=new Color3(.42,.46,.5);
const mats={};
function material(name,color,{emissive=null,alpha=1,spec=.08}={}){if(mats[name])return mats[name];const m=new StandardMaterial(name,scene);m.diffuseColor=color;m.specularColor=new Color3(spec,spec,spec);m.specularPower=24;m.alpha=alpha;if(emissive)m.emissiveColor=emissive;m.freeze();return mats[name]=m}
function box(name,parent,pos,scale,mat){const m=MeshBuilder.CreateBox(name,{size:1},scene);m.position.set(...pos);m.scaling.set(...scale);m.material=mat;if(parent)m.parent=parent;return m}
function sphere(name,parent,pos,scale,mat,segments=10){const m=MeshBuilder.CreateSphere(name,{diameter:1,segments},scene);m.position.set(...pos);m.scaling.set(...scale);m.material=mat;if(parent)m.parent=parent;return m}
function cyl(name,parent,pos,scale,mat,tess=10){const m=MeshBuilder.CreateCylinder(name,{height:1,diameter:1,tessellation:tess},scene);m.position.set(...pos);m.scaling.set(...scale);m.material=mat;if(parent)m.parent=parent;return m}
function shadow(parent,r=.7){const s=cyl('shadow',parent,[0,.025,0],[r,.025,r],material('shadow',new Color3(.04,.07,.04),{alpha:.22}),18);return s}
const M={ground:material('ground',new Color3(.48,.68,.38)),path:material('path',new Color3(.76,.67,.48)),wall:material('wall',new Color3(.73,.67,.58)),roof:material('roof',new Color3(.42,.17,.12)),glass:material('glass',new Color3(.23,.52,.7),{emissive:new Color3(.04,.12,.18)}),door:material('door',new Color3(.24,.12,.07)),water:material('water',new Color3(.16,.48,.69),{emissive:new Color3(.02,.08,.12)}),wood:material('wood',new Color3(.35,.18,.08)),leaf:material('leaf',new Color3(.16,.43,.18)),skin:material('skin',new Color3(.88,.7,.55)),hair:material('hair',new Color3(.12,.08,.055)),player:material('player',new Color3(.1,.25,.48)),green:material('green',new Color3(.16,.42,.2)),blue:material('blue',new Color3(.18,.37,.55)),rose:material('rose',new Color3(.65,.24,.35)),white:material('white',new Color3(.92,.9,.82)),black:material('black',new Color3(.02,.025,.02)),purple:material('purple',new Color3(.45,.24,.55)),smog:material('smog',new Color3(.2,.34,.22)),flame:material('flame',new Color3(1,.42,.04),{emissive:new Color3(1,.18,.01)}),smoke:material('smoke',new Color3(.42,.44,.43),{alpha:.28}),target:material('target',new Color3(.75,.07,.025),{emissive:new Color3(.75,.06,.02)})};

// Environment: simple PBR-like shapes, kept intentionally light for phones.
box('ground',null,[0,-.15,0],[30,.3,24],M.ground);box('pathA',null,[-1,-.02,0],[3.4,.05,22],M.path);box('pathB',null,[1,-.015,3],[24,.05,2.8],M.path);
const hotel=new TransformNode('hotel',scene);hotel.position.set(-8,0,-6);box('hotelBody',hotel,[0,1.7,0],[6.2,3.4,3.8],M.wall);box('roof',hotel,[0,3.55,0],[6.8,.5,4.4],M.roof);box('door',hotel,[0,1,-1.94],[1.1,2,.12],M.door);[-2,0,2].forEach(x=>box('window',hotel,[x,2.35,-1.96],[1.05,.8,.08],M.glass));
const pond=MeshBuilder.CreateCylinder('pond',{height:.08,diameter:5.5,tessellation:24},scene);pond.position.set(4,.02,-4.5);pond.material=M.water;
function tree(x,z,s=1){const r=new TransformNode('tree',scene);r.position.set(x,0,z);cyl('trunk',r,[0,1.25,0],[.55*s,2.5*s,.55*s],M.wood);sphere('crown',r,[0,3.1*s,0],[1.65*s,1.3*s,1.65*s],M.leaf);return r}
[[-12,-1,1.05],[-10,5,.9],[-4,9,1],[4,9,.95],[12,5,1.05],[12,-7,.9],[1,-10,.95]].forEach(v=>tree(...v));
function bench(x,z){const r=new TransformNode('bench',scene);r.position.set(x,0,z);box('seat',r,[0,.55,0],[2.2,.18,.55],M.wood);box('back',r,[0,1.15,.22],[2.2,.75,.14],M.wood);[-.75,.75].forEach(px=>box('leg',r,[px,.27,0],[.18,.55,.18],M.black));return r}bench(4.6,-1.2);

function human(name,pos,shirt){const r=new TransformNode(name,scene);r.position.set(...pos);shadow(r,.68);box('torso',r,[0,1.35,0],[.86,1.25,.48],shirt);sphere('head',r,[0,2.35,0],[.62,.72,.62],M.skin,12);sphere('hair',r,[0,2.65,.03],[.65,.34,.65],M.hair,10);[-.52,.52].forEach(x=>{cyl('arm',r,[x,1.38,0],[.22,1.15,.22],shirt);cyl('leg',r,[x*.48,.48,0],[.27,.95,.27],M.black)});return r}
const player=human('player',[-7.2,0,-3],M.player),gardener=human('gardener',[-2.5,0,.3],M.green),keeper=human('pondKeeper',[2.8,0,.1],M.blue),traveler=human('traveler',[7,0,-1.2],M.rose);keeper.setEnabled(false);traveler.setEnabled(false);

function woodsBoss(){const r=new TransformNode('WOODS',scene);r.position.set(9,0,6.5);shadow(r,1.2);cyl('trunk',r,[0,1.8,0],[1.15,3.6,1.15],M.wood,12);[-1,1].forEach(side=>{const a=cyl('branch',r,[side*1.25,2.15,0],[.42,2.7,.42],M.wood);a.rotation.z=side*.75;sphere('leaf',r,[side*2.1,3.15,0],[1.2,.9,1.1],M.leaf)});sphere('crown',r,[0,4.05,0],[1.55,1.05,1.45],M.leaf);for(let i=0;i<3;i++){const v=MeshBuilder.CreateTorus('vine',{diameter:1.8+i*.2,thickness:.1,tessellation:18},scene);v.parent=r;v.position.y=1.1+i*.65;v.material=M.green}return r}
function eyeBoss(){const r=new TransformNode('EYE',scene);r.position.set(8,0,-4.5);shadow(r,1.15);cyl('body',r,[0,1.8,0],[1.25,3.4,1.25],M.white,12);[-1,1].forEach(side=>{const a=cyl('branch',r,[side*1.2,2.1,0],[.35,2.3,.35],M.wood);a.rotation.z=side*.72});const points=[[0,2.9,-.62],[-.55,2.2,-.58],[.55,2.15,-.58],[-.4,1.45,-.58],[.4,1.3,-.58]];for(const [x,y,z] of points){sphere('eyeWhite',r,[x,y,z],[.42,.3,.18],M.white,12);sphere('pupil',r,[x,y,z-.17],[.14,.14,.09],M.black,10)};for(let i=0;i<3;i++){const leaf=sphere('eyeLeaf',r,[Math.cos(i*2.1)*1.1,3.8+Math.sin(i)*.35,0],[.65,.35,.3],M.green);leaf.rotation.z=i}return r}
function smogBoss(){const r=new TransformNode('SMOG',scene);r.position.set(10.5,0,-6);shadow(r,1.1);cyl('body',r,[0,1.8,0],[1.05,3.5,1.05],M.smog,12);[-1,1].forEach(side=>{const a=cyl('arm',r,[side*1.1,2,0],[.35,2.2,.35],M.smog);a.rotation.z=side*.65});cyl('candle',r,[0,4.05,0],[.38,1.15,.38],M.white,12);sphere('flame',r,[0,4.85,0],[.36,.58,.36],M.flame,10);const smoke=[];for(let i=0;i<4;i++)smoke.push(sphere('smoke',r,[Math.sin(i)*.5,5.35+i*.48,0],[.72,.55,.72],M.smoke,10));r.metadata={smoke};return r}
const woods=woodsBoss(),eye=eyeBoss(),smog=smogBoss();woods.setEnabled(false);eye.setEnabled(false);smog.setEnabled(false);

const targetRoot=new TransformNode('target',scene);const ring=MeshBuilder.CreateTorus('targetRing',{diameter:2.2,thickness:.16,tessellation:24},scene);ring.parent=targetRoot;ring.position.y=.08;ring.material=M.target;const arrow=MeshBuilder.CreateCylinder('targetArrow',{height:.8,diameterTop:0,diameterBottom:.7,tessellation:4},scene);arrow.parent=targetRoot;arrow.position.y=3.4;arrow.rotation.z=Math.PI;arrow.material=M.target;
const hemi=new HemisphericLight('ambient',new Vector3(0,1,0),scene);hemi.intensity=.72;const sun=new DirectionalLight('sun',new Vector3(-.55,-1,-.4),scene);sun.intensity=1.0;sun.diffuse=new Color3(1,.87,.7);
const camera=new FreeCamera('camera',new Vector3(3,10,12),scene);camera.minZ=.1;camera.maxZ=80;camera.fov=.82;camera.setTarget(player.position.add(new Vector3(0,1.1,0)));

let stage=0,target=gardener,sessionTime=0,sessionComplete=false,jumpT=0,jumping=false,woodsHits=0,woodsClock=0,woodsVulnerable=false,eyeHits=0,eyeHitCooldown=0,eyeDashClock=0,smogClock=0,smogCycles=0,lastSecond=-1;
const keys=new Set(),mobileMove={up:false,down:false,left:false,right:false};
function setStage(n){stage=n;window.__gameState.stage=n;talkBtn.classList.remove('hot');trapBtn.classList.remove('hot');strikeBtn.classList.remove('hot');if(n===0){target=gardener;setMission('① 정원사에게 가기 → E 말걸기');}if(n===1){woods.setEnabled(true);target=woods;setMission('② WOODS까지 이동하기','WOODS는 눈 대신 소리에 반응해요');say('정원사: <b>woods는 눈이 없고 작은 소리를 잘 들어.</b>',10000);}if(n===2){target=woods;showBoss('WOODS',woodsHits,3,'공격 후 노란 안내가 뜨면 Q 함정');setMission('③ WOODS 공격 피하기 → Q 함정 3번');say('WOODS가 공격한 뒤 잠깐 멈출 때 <b>Q 함정</b>을 눌러!',9000);}if(n===3){bossHud.classList.add('hidden');keeper.setEnabled(true);target=keeper;setMission('④ 연못 관리인에게 가기 → E 말걸기');say('WOODS는 쓰러져도 바로 사라지지 않고 정원에 남아 있어요.',8000);}if(n===4){eye.setEnabled(true);target=eye;setMission('⑤ EYE에게서 피하기 → F 베기 3번','EYE가 실제로 플레이어를 쫓아와요');showBoss('EYE',eyeHits,3,'가까이 왔을 때 F 베기');say('EYE가 이제 <b>직접 쫓아와요.</b> 거리를 만들고 가까워졌을 때 F!',9000);}if(n===5){bossHud.classList.add('hidden');traveler.setEnabled(true);target=traveler;setMission('⑥ 여행객에게 가기 → E 말걸기');}if(n===6){smog.setEnabled(true);target=smog;setMission('⑦ SMOG 가까이에서 3번의 패턴 관찰하기','SMOG는 금방 사라지지 않아요');showBoss('SMOG',0,3,'촛불 → 연기 → 열기 변화를 관찰');say('SMOG는 이번엔 사라지지 않아요. <b>촛불·연기·열기</b> 변화를 천천히 봐.',10000);}if(n===7){bossHud.classList.add('hidden');target=null;targetRoot.setEnabled(false);setMission('✓ 미션 완료 · 7분까지 자유 탐험','보스와 낮/밤 변화를 더 살펴봐도 돼요');say('미션은 끝! 게임은 바로 닫히지 않아요. <b>7분 탐험 시간</b>까지 자유롭게 돌아다녀 봐.',12000);emit('missions_complete',{elapsed:sessionTime});}emit('stage',{stage:n});updateActionButtons()}
function showBoss(name,hits,total,tip){bossHud.classList.remove('hidden');bossName.textContent=name;bossTip.textContent=tip;bossHp.style.width=`${Math.max(0,100-hits/total*100)}%`}
function distTo(node){return node?Vector3.Distance(player.position,node.position):999}
function near(node,r=2.8){return distTo(node)<=r}
function talk(){if(stage===0&&near(gardener,2.8)){emit('npc',{name:'gardener'});setStage(1);return}if(stage===3&&near(keeper,2.8)){emit('npc',{name:'pondKeeper'});say('연못 관리인: <b>EYE는 빠르게 달려와. 거리를 만들고 타이밍을 봐.</b>',10000);setStage(4);return}if(stage===5&&near(traveler,2.8)){emit('npc',{name:'traveler'});say('여행객: <b>SMOG는 가까이 가면 뜨거워져. 천천히 관찰해.</b>',10000);setStage(6);return}toast('지금은 말 걸 사람이 가까이에 없어요')}
function trap(){if(stage!==2){toast('지금은 함정을 쓸 차례가 아니에요');return}if(!near(woods,6)){toast('WOODS에 조금 더 가까이 가요');return}if(!woodsVulnerable){toast('지금은 공격 중! 먼저 피했다가 멈추는 순간을 봐요');return}woodsHits++;woodsVulnerable=false;woods.scaling.y=.86;setTimeout(()=>woods.scaling.y=1,350);showBoss('WOODS',woodsHits,3,woodsHits<3?'좋아! 다음 공격 뒤 Q':'WOODS 진정 완료');emit('boss_hit',{boss:'woods',hits:woodsHits});toast(`함정 성공 ${woodsHits}/3`);if(woodsHits>=3)setTimeout(()=>setStage(3),1200)}
function strike(){if(stage!==4){toast('지금은 베기를 쓸 차례가 아니에요');return}if(eyeHitCooldown>0){toast('조금만 기다렸다 다시!');return}if(!near(eye,3.1)){toast('EYE가 가까워졌을 때 F 베기');return}eyeHits++;eyeHitCooldown=2.2;eye.scaling.scaleInPlace(.92);setTimeout(()=>eye.scaling.setAll(1),300);showBoss('EYE',eyeHits,3,eyeHits<3?'추격을 피하고 다시 가까워졌을 때 F':'EYE 진정 완료');emit('boss_hit',{boss:'eye',hits:eyeHits});toast(`베기 성공 ${eyeHits}/3`);if(eyeHits>=3)setTimeout(()=>setStage(5),1200)}
function jump(){if(jumping)return;jumping=true;jumpT=0;emit('jump')}
function doAction(a){if(a==='talk')talk();if(a==='trap')trap();if(a==='strike')strike();if(a==='jump')jump()}

addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(['arrowup','arrowdown','arrowleft','arrowright',' ','e','q','f','w','a','s','d'].includes(k))e.preventDefault();keys.add(k);if(!e.repeat){if(k==='e')talk();if(k==='q')trap();if(k==='f')strike();if(k===' ')jump()}});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
document.querySelectorAll('[data-move]').forEach(b=>{const d=b.dataset.move;const on=e=>{e.preventDefault();mobileMove[d]=true};const off=e=>{e.preventDefault();mobileMove[d]=false};b.addEventListener('pointerdown',on);b.addEventListener('pointerup',off);b.addEventListener('pointercancel',off);b.addEventListener('pointerleave',off)});document.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('pointerup',e=>{e.preventDefault();doAction(b.dataset.action)}));
function updateActionButtons(){talkBtn.classList.toggle('dim',![0,3,5].includes(stage));trapBtn.classList.toggle('dim',stage!==2);strikeBtn.classList.toggle('dim',stage!==4);talkBtn.classList.toggle('hot',[0,3,5].includes(stage)&&near(target,3));trapBtn.classList.toggle('hot',stage===2&&woodsVulnerable&&near(woods,6));strikeBtn.classList.toggle('hot',stage===4&&near(eye,3.1))}
function updateDayNight(){const t=(sessionTime%120)/120,dayness=(Math.cos(t*Math.PI*2)+1)/2;scene.clearColor=new Color4(.045+.52*dayness,.065+.67*dayness,.12+.78*dayness,1);sun.intensity=.18+.95*dayness;hemi.intensity=.28+.5*dayness;if(t<.18||t>.82)timeBadge.textContent='☀️ 낮';else if(t<.34)timeBadge.textContent='🌇 해질녘';else if(t<.68)timeBadge.textContent='🌙 밤';else timeBadge.textContent='🌅 새벽'}
function updateTimer(){const sec=Math.floor(sessionTime),m=String(Math.floor(sec/60)).padStart(2,'0'),s=String(sec%60).padStart(2,'0');timerEl.textContent=`${m}:${s} / 07:00`;if(sec!==lastSecond){lastSecond=sec;updateDayNight()}if(sessionTime>=420&&!sessionComplete){sessionComplete=true;toast('🎉 7분 탐험 완료!',4000);say('7분 동안 잘 탐험했어! 원하면 계속 돌아다녀도 돼.',12000);emit('session_complete',{seconds:Math.floor(sessionTime)})}}
function updateTarget(){if(!target){targetRoot.setEnabled(false);distanceEl.textContent='자유롭게 둘러봐도 돼요';return}targetRoot.setEnabled(true);targetRoot.position.copyFrom(target.position);arrow.position.y=3.4+Math.sin(sessionTime*3)*.25;const d=Math.round(distTo(target));distanceEl.textContent=d<=3?'도착! 지금 행동 버튼을 눌러요':`목표까지 약 ${d}m · 빨간 표시를 따라가요`}
function updatePlayer(dt){let x=0,z=0;if(keys.has('a')||keys.has('arrowleft')||mobileMove.left)x-=1;if(keys.has('d')||keys.has('arrowright')||mobileMove.right)x+=1;if(keys.has('w')||keys.has('arrowup')||mobileMove.up)z-=1;if(keys.has('s')||keys.has('arrowdown')||mobileMove.down)z+=1;if(x||z){const l=Math.hypot(x,z);x/=l;z/=l;player.position.x=Math.max(-14,Math.min(14,player.position.x+x*dt*4.2));player.position.z=Math.max(-11,Math.min(11,player.position.z+z*dt*4.2));player.rotation.y=Math.atan2(x,z);emitMoveCooldown=Math.max(0,emitMoveCooldown-dt)}if(jumping){jumpT+=dt;player.position.y=Math.sin(Math.min(1,jumpT/.7)*Math.PI)*1.15;if(jumpT>=.7){player.position.y=0;jumping=false}}}
let emitMoveCooldown=0;
function updateWoods(dt){if(stage!==2)return;woodsClock=(woodsClock+dt)%7;if(woodsClock<1.6){woodsVulnerable=false;woods.rotation.z=Math.sin(woodsClock*5)*.08;bossTip.textContent='덩굴이 움직여요 · 피하기'}else if(woodsClock<3.8){woodsVulnerable=false;woods.rotation.z=Math.sin(woodsClock*8)*.16;bossTip.textContent='공격 중 · 이동해서 피하기'}else{woodsVulnerable=true;woods.rotation.z*=.88;bossTip.textContent='지금! Q 함정';}if(near(woods,2.3)&&woodsClock<3.8&&woodsClock>1.6){toast('WOODS 공격! 조금 떨어져요',900)}}
function updateEye(dt){if(stage!==4)return;eyeHitCooldown=Math.max(0,eyeHitCooldown-dt);eyeDashClock=(eyeDashClock+dt)%8;const d=player.position.subtract(eye.position);d.y=0;const len=d.length();if(len>1.9){d.normalize();const speed=eyeDashClock>5.7&&eyeDashClock<6.5?4.4:1.75;eye.position.addInPlace(d.scale(dt*speed));eye.rotation.y=Math.atan2(d.x,d.z)}bossTip.textContent=eyeDashClock>5.7&&eyeDashClock<6.5?'돌진! 옆으로 피하기':'EYE가 따라오는 중 · 가까우면 F'}
function updateSmog(dt){if(stage<6)return;smogClock+=dt;const phase=smogClock%12;const smoke=smog.metadata.smoke;for(let i=0;i<smoke.length;i++){smoke[i].position.y=5.25+i*.48+Math.sin(sessionTime*1.6+i)*.18;smoke[i].position.x=Math.sin(sessionTime*.8+i)*.55}if(stage===6){if(phase<4)bossTip.textContent='1단계 · 촛불이 강해져요';else if(phase<8)bossTip.textContent='2단계 · 연기가 모여요';else bossTip.textContent='3단계 · 가까이 가면 뜨거워져요';const cycle=Math.floor(smogClock/12);if(cycle>smogCycles){smogCycles=cycle;showBoss('SMOG',Math.min(smogCycles,3),3,smogCycles<3?`패턴 관찰 ${smogCycles}/3`:'관찰 완료 · SMOG는 그대로 남아 있어요');emit('smog_cycle',{count:smogCycles});if(smogCycles>=3)setStage(7)}}}

let prev=performance.now(),statClock=0;scene.onBeforeRenderObservable.add(()=>{const now=performance.now(),dt=Math.min(.05,(now-prev)/1000);prev=now;sessionTime+=dt;statClock+=dt;updatePlayer(dt);if(stage===1&&near(woods,7))setStage(2);updateWoods(dt);updateEye(dt);updateSmog(dt);updateTarget();updateTimer();updateActionButtons();const desired=player.position.add(new Vector3(8.8,8.5,10.5));camera.position=Vector3.Lerp(camera.position,desired,.08);camera.setTarget(player.position.add(new Vector3(0,1.25,0)));if(statClock>=.5){statClock=0;window.__gameState.ready=true;window.__gameState.fps=+engine.getFps().toFixed(1);window.__gameState.session=+sessionTime.toFixed(1);window.__gameState.stage=stage}});
engine.runRenderLoop(()=>scene.render());addEventListener('resize',()=>engine.resize());setStage(0);setTimeout(()=>{loading.classList.add('hide');setTimeout(()=>loading.remove(),450);window.__gameState.ready=true;emit('ready',{engine:'Babylon.js'});},350);say('정원사를 찾아가 볼까? 가까이 가면 <b>E 말걸기</b>가 밝아져요.',10000);
